var numeros1 = Number(prompt('digite o primeiro número para soma:'))
var numeros2 = Number(prompt('digite o segundo número para soma:'))
console.log(numeros1 + numeros2)
var numerosub1 = Number(prompt('digite o primeiro número para subtração:'))
var numerosub2 = Number(prompt('digite o segundo número para subtração:'))
console.log(numerosub1 - numerosub2)
var numerom1 = Number(prompt('digite o primeiro número para multiplicação:'))
var numerom2 = Number(prompt('digite o segundo número para multiplicação:'))
console.log(numerom1 * numerom2)
var numerod1 = Number(prompt('digite o primeiro número para divisão:'))
var numerod2 = Number(prompt('digite o segundo número para divisão:'))
console.log(numerod1 / numerod2)